##
# Renovate Bot self-hosted instance configuration for CircleCI.
#
# Add RENOVATE_TOKEN as an environment variable with GitHub access token in UI.
version: 2
jobs:
  renovatebot:
    docker:
      - image: renovate/renovate:latest
        environment:
          # Update the value of RENOVATE_GIT_AUTHOR with your own.
          RENOVATE_GIT_AUTHOR: 'RenovateBot Self Hosted <renovatebot@drevops.com>'
          # Update the value of RENOVATE_REPOSITORIES with your own repository name.
          RENOVATE_REPOSITORIES: 'drevops/renovate-drupal-example'
          RENOVATE_DEPENDENCY_DASHBOARD_TITLE: 'RenovateBot Dependency Dashboard (self-hosted) by CircleCI'
          RENOVATE_DEPENDENCY_DASHBOARD: true
          RENOVATE_PLATFORM: 'github'
          RENOVATE_AUTODISCOVER: false
          RENOVATE_DRY_RUN: false
          LOG_LEVEL: debug
    steps:
      - checkout
      - run: renovate-config-validator
      - run: renovate

workflows:
  version: 2
  feature:
    jobs:
      - renovatebot:
          filters:
            branches:
              only: /feature\/.+/

  renovatebot:
    triggers:
      - schedule:
          cron: "15 * * * *" # Triggers every hour for demonstration purposes. Change this schedule to a daily run.
          filters:
            branches:
              only:
                - main
    jobs:
      - renovatebot
