name: Renovate
on:
  schedule:
    - cron: '45 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.154.4
        env:
          # Update the value of RENOVATE_GIT_AUTHOR with your own.
          RENOVATE_GIT_AUTHOR: 'Renovate Self Hosted <renovatebot@drevops.com>'
          RENOVATE_DEPENDENCY_DASHBOARD_TITLE: 'Renovate Dependency Dashboard (self-hosted) by GitHub Actions'
          RENOVATE_DEPENDENCY_DASHBOARD: true
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_PLATFORM: 'github'
          RENOVATE_AUTODISCOVER: false
          RENOVATE_DRY_RUN: false
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
